services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    depends_on:
      - backend
    command: npm run start

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    volumes:
      - ./back:/app
    environment:
      - PYTHONPATH=/app
